# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
pod 'BTNavigationDropdownMenu'

target 'BTNavigationDropdownMenu' do

end

target 'BTNavigationDropdownMenuTests' do

end

target 'BTNavigationDropdownMenuUITests' do

end

